FROM python:3.11-slim

ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple \
    PIP_DEFAULT_TIMEOUT=1000 \
    PIP_NO_CACHE_DIR=1

WORKDIR /workdir

COPY requirements.txt requirements_dev.txt setup.py ./

RUN pip install --upgrade pip setuptools wheel

RUN pip install -r requirements.txt && pip install .

COPY app/ ./app/
COPY ml/ ./ml/

CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "80"]